'''
This defines the Indaleko Services schema.

Project Indaleko
Copyright (C) 2024 Tony Mason

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''
import json
import jsonschema
from jsonschema import validate, Draft202012Validator, exceptions

from IndalekoRecordSchema import IndalekoRecordSchema

class IndalekoServicesSchema(IndalekoRecordSchema):
    '''This class defines the schema for Indaleko Services.'''

    @staticmethod
    def is_valid_services(indaleko_services : dict) -> bool:
        '''Given a dict, determine if it is a valid Indaleko Services.'''
        assert isinstance(indaleko_services, dict), 'services must be a dict'
        valid = False
        try:
            validate(instance=indaleko_services, schema=IndalekoServicesSchema.get_schema())
            valid = True
        except jsonschema.exceptions.ValidationError as error:
            print(f'Validation error: {error.message}')
        return valid

    @staticmethod
    def get_schema():
        services_schema = {
            "$schema": "https://json-schema.org/draft/2020-12/schema#",
            "$id": "https://activitycontext.work/schema/serviceprovider.json",
            "title": "Service provider schema",
            "description": "This schema describes information about service providers within the Indaleko system.",
            "type": "object",
            "rule" : {
                "properties": {
                    "Identifier": {
                        "description": "This is the UUID of the given source for this metadata.",
                        "type": "string",
                        "format": "uuid"
                    },
                    "Version": {
                        "description": "This is the version of the source provider. Versioning allows evolution of the data generated by the source.",
                        "type": "string",
                    },
                    "Name": {
                        "description": "This is the (unique) name of the source provider.",
                        "type": "string"
                    },
                    "Type": {
                        "description": "This is the type of the service provider.",
                        "type": "string"
                    },
                },
                "required": ["Identifier", "Version", "Name", "Type"],
            }
        }
        assert 'Record' not in services_schema['rule']['properties'], 'Record must not be specified.'
        services_schema['rule']['properties']['Record'] = IndalekoRecordSchema.get_schema()['rule']
        services_schema['rule']['required'].append('Record')
        return services_schema

def main():
    '''Test code for IndalekoObjectSchema.'''
    if IndalekoServicesSchema.is_valid_schema(IndalekoServicesSchema.get_schema()):
        print('Schema is valid.')
    print(json.dumps(IndalekoServicesSchema.get_schema(), indent=4))

if __name__ == "__main__":
    main()

