IndalekoMachineConfigSchema = {
        '''
        This schema relates to the machine configuration collection,
        which captures meta-data about the machine where the data was indexed.
        '''
        "$schema": "https://json-schema.org/draft/2020-12/schema#",
        "$id": "https://activitycontext.work/schema/machineconfig.json",
        "title": "Data source schema",
        "description": "This schema describes information about the machine where the data was indesxed.",
        "type": "object",
        "rule" : {
            "platform" : {
                "type" : "object",
                "properties" : {
                    "software" : {
                        "type" : "object",
                        "properties" : {
                            "OS" : {
                                "type" : "string",
                                "description" : "Name of the software.",
                            },
                            "version" : {
                                "type" : "string",
                                "description" : "Version of the software.",
                            },
                        },
                        "required" : ["OS", "version"],
                    },
                    "hardware" : {
                        "type" : "object",
                        "properties" : {
                            "CPU" : {
                                "type" : "string",
                                "description" : "Processor Architecture.",
                            },
                            "version" : {
                                "type" : "string",
                                "description" : "Version of the hardware.",
                            },
                        },
                        "required" : ["CPU", "version"],
                    },
                },
            },
            "properties": {
                "source": {
                    "description": "This is the UUID of the given source for this metadata.",
                    "type": "string",
                    "format": "uuid"
                },
                "version": {
                    "description": "This is the version of the source provider. Versioning allows evolution of the data generated by the source.",
                    "type": "string",
                },
                "captured" : {
                    "Label" : {
                        "type" : "string",
                        "description" : "UUID representing the semantic meaning of this timestamp.",
                        "format": "uuid",
                    },
                    "Value" : {
                        "type" : "string",
                        "description" : "Timestamp in ISO date and time format.",
                        "format" : "date-time",
                    },
                },
            },
            "required" : ["source", "version", "captured"],
        }
    }
