'''
This defines the Indaleko Services schema.

Project Indaleko
Copyright (C) 2024 Tony Mason

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''
import jsonschema
import apischema

from uuid import UUID

from IndalekoRecordSchema import IndalekoRecordSchema
from IndalekoService import IndalekoService
from IndalekoServiceDataModel import IndalekoServiceDataModel

class IndalekoServiceSchema(IndalekoRecordSchema):
    '''This class defines the schema for Indaleko Services.'''

    def __init__(self, **kwargs):
        '''Initialize the Services schema.'''
        if not hasattr(self, 'data_model'):
            self.data_model = IndalekoServiceDataModel()
        if not hasattr(self, 'base_type'):
            self.base_type = IndalekoServiceDataModel.IndalekoService
        services_rules = apischema.json_schema.deserialization_schema(IndalekoServiceDataModel.IndalekoService,
                                                                    additional_properties=True)
        if not hasattr(self, 'rules'):
            self.rules = services_rules
        else:
            self.rules.update(services_rules)
        schema_id = kwargs.get('schema_id', "https://activitycontext.work/schema/serviceprovider.json")
        schema_title = kwargs.get('schema_title', "Service provider schema")
        schema_description = kwargs.get('schema_description', "This schema describes information about service providers within the Indaleko system.")
        super().__init__(
            schema_id = schema_id,
            schema_title = schema_title,
            schema_description = schema_description,
            data_model = self.data_model,
            base_type = self.base_type,
            schema_rules = services_rules
        )

    @staticmethod
    def is_valid_services(indaleko_services : dict) -> bool:
        '''Given a dict, determine if it is a valid Indaleko Services.'''
        assert isinstance(indaleko_services, dict), 'services must be a dict'
        valid = False
        try:
            jsonschema.validate(instance=indaleko_services,
                                schema=IndalekoServiceSchema.get_old_schema())
            valid = True
        except jsonschema.exceptions.ValidationError as error:
            print(f'Validation error: {error.message}')
        return valid

    @staticmethod
    def get_old_schema():
        services_schema = {
            "$schema": "https://json-schema.org/draft/2020-12/schema#",
            "$id": "https://activitycontext.work/schema/serviceprovider.json",
            "title": "Service provider schema",
            "description": "This schema describes information about service providers within the Indaleko system.",
            "type": "object",
            "rule" : {
                "properties": {
                    "Identifier": {
                        "description": "This is the UUID of the given source for this metadata.",
                        "type": "string",
                        "format": "uuid"
                    },
                    "Version": {
                        "description": "This is the version of the source provider. Versioning allows evolution of the data generated by the source.",
                        "type": "string",
                    },
                    "Name": {
                        "description": "This is the (unique) name of the source provider.",
                        "type": "string"
                    },
                    "Type": {
                        "description": "This is the type of the service provider.",
                        "type": "string"
                    },
                },
                "required": ["Identifier", "Version", "Name", "Type"],
            }
        }
        assert 'Record' not in services_schema['rule']['properties'], 'Record must not be specified.'
        services_schema['rule']['properties']['Record'] = IndalekoRecordSchema.get_old_schema()['rule']
        services_schema['rule']['required'].append('Record')
        return services_schema

    @staticmethod
    def get_service(identifier : UUID) -> IndalekoServiceDataModel.IndalekoService:
        '''Return an IndalekoService object.'''
        service = IndalekoServiceDataModel.IndalekoService(
            Record = None,
            Identifier = identifier,
            Version = '1.0.0',
            Name = 'Test Service',
            Type = 'Test'
        )
        return service

def main():
    '''Test code for IndalekoObjectSchema.'''
    services_schema = IndalekoServiceSchema()
    services_schema.schema_detail()

if __name__ == "__main__":
    main()
