
import json
import uuid
import datetime
from IndalekoRecord import IndalekoRecord
import argparse

class IndalekoSource(IndalekoRecord):
    '''
    This schema defines the fields that are required as part of this
    metadata.  Additional (optional) metadata can be included.
    '''
    Schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema#",
        "$id": "https://activitycontext.work/schema/source.json",
        "title": "Data source schema",
        "description": "This schema describes information about the sources of metadata within the Indaleko system.",
        "type": "object",
        "properties": {
            "identifier": {
                "description": "This is the UUID of the given source for this metadata.",
                "type": "string",
                "format": "uuid"
            },
            "version": {
                "description": "This is the version of the source provider. Versioning allows evolution of the data generated by the source.",
                "type": "string",
            },
        },
        "required": ["identifier", "version"]
    }

    def __init__(self, identifier : uuid.UUID, version : str, description : str) -> None:
        super().__init__(b'',
                         {'Description' : description},
                         {
                            'Identifier' : str(uuid.UUID),
                            'Version' : version,
                         })


def main():
    source_uuid = '2a44214d-fa65-4175-a14b-928102cbca3f'
    parser = argparse.ArgumentParser()
    parser.add_argument('--description', type=str, default='This is a test description.', help='The description of the source.')
    args = parser.parse_args()
    source = IndalekoSource(uuid.UUID(source_uuid), '1.0', args.description)
    print(f'Source:\n{source.to_json()}')

if __name__ == "__main__":
    main()
