'''
This module defines the data schema for the Indaleko Source records.
These are used to capture information about the source of information in the
database.

Project Indaleko
Copyright (C) 2024 Tony Mason

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''
import json
from IndalekoRecordSchema import IndalekoRecordSchema

class IndalekoSourceSchema(IndalekoRecordSchema):
    '''Define the schema for use with the Source collection.'''

    @staticmethod
    def get_schema():
        source_schema = {
            "$schema": "https://json-schema.org/draft/2020-12/schema#",
            "$id": "https://activitycontext.work/schema/source.json",
            "title": "Data source schema",
            "description": "This schema describes information about the sources of metadata within the Indaleko system.",
            "type": "object",
            "rule" : {
                "properties": {
                    "Identifier": {
                        "description": "This is the UUID of the given source for this metadata.",
                        "type": "string",
                        "format": "uuid"
                    },
                    "Version": {
                        "description": "This is the version of the source provider. Versioning allows evolution of the data generated by the source.",
                        "type": "string",
                    },
                },
                "required": ["Identifier", "Version"]
            }
        }
        assert 'Record' not in source_schema, 'Record must not be specified.'
        source_schema['rule']['properties']['Record'] = IndalekoRecordSchema.get_schema()
        source_schema['rule']['required'].append('Record')
        return source_schema

def main():
    """Test the IndalekoMachineConfigSchema class."""
    if IndalekoSourceSchema.is_valid_schema(IndalekoSourceSchema.get_schema()):
        print('Schema is valid.')
    print(json.dumps(IndalekoSourceSchema.get_schema(), indent=4))

if __name__ == "__main__":
    main()


